# Generated by Django 2.0.2 on 2018-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='useragent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
