# Generated by Django 2.0.2 on 2018-02-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_useragent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Visit',
        ),
    ]
